server:
    port: 8081

spring:
    application:
        name: service-user
    datasource:
        url: jdbc:postgresql://localhost:5432/userdb
        username: postgres
        password: rootroot
    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
